version: '3.4'

services:
  managementapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBus__ServiceName=ManagementApi
      - RabbitMq__UserName=${EVENT_BUS:-admin}
      - RabbitMq__Password=${EVENT_BUS:-admin}
      - RabbitMq__HostName=rabbit1
      - Storage__ConnectionString=${CONNECTION_STRING:-Server=postgres;Port=5432;Database=postgres;Username=postgres;Password=postgres;}
    ports:
      - "5010:80"

  userapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EventBus__ServiceName=UserApi
      - RabbitMq__UserName=${EVENT_BUS:-admin}
      - RabbitMq__Password=${EVENT_BUS:-admin}
      - RabbitMq__HostName=rabbit1
    ports:
      - "6010:80"

